### ISSUE TITLE
Large CSS selector grouping (8+) throws an exception.

### ISSUE THREAD

**Issue by jakubstrama** [GoogleChrome/devtools-docs#294]
Following selector grouping causes devttools Elements to show no style while analysing the selected element. *(Chrome Version 44.0.2403.125 m)*

## CSS
```
.remove-link, .edit-link, .done-link, .cancel-link, .remove-link > i, .edit-link > i, .done-link > i, .cancel-link > i {
  color: #c4c4c4;
  transition: all 0.2s;
}
```
## Markup
```
<a  href="#" ... class="ui-commandlink ui-widget remove-link pull-right">
	<i class="fa fa-times"></i>
</a>
```

![emptyselection](https://cloud.githubusercontent.com/assets/6832946/9006492/1547e81e-3788-11e5-9b7c-7af665438422.png)

While analyzing devtools with <kbd>ctrl</kbd> + <kbd>shift</kbd> + <kbd>i</kbd> inspector, following exception is thrown after clicking on ```<i>```  tag:
```
TypeError: Cannot read property 'range' of undefined
    at Function.WebInspector.StylePropertiesSection.createRuleOriginNode (chrome-devtools://devtools/bundled/elements_module.js:1477:183)
    at Object.WebInspector.StylePropertiesSection._updateRuleOrigin (chrome-devtools://devtools/bundled/elements_module.js:1472:117)
    at Object.WebInspector.StylePropertiesSection (chrome-devtools://devtools/bundled/elements_module.js:1363:198)
    at Object.WebInspector.StylesSidebarPane._rebuildSectionsForMatchedStyleRules (chrome-devtools://devtools/bundled/elements_module.js:1300:13)
    at Object.WebInspector.StylesSidebarPane._innerRebuildUpdate (chrome-devtools://devtools/bundled/elements_module.js:1274:33)
```
It looks like the method ```rule.matchingSelectors``` returns an index that is out of bounds of ```rule.selectors[firstMatchingIndex]```

**Comment by Garbee** [comment]
Please  file a bug in the [chromium issue tracker](http://crbug.com). This repo is for the documentation only.
